# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - easycharter-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Enable long paths
        run: |
          git config --system core.longpaths true

      - name: Install dependencies and build
        run: |
          # Install all dependencies first (including dev dependencies needed for build)
          npm ci
          # Run the build
          npm run build --if-present
          # Remove dev dependencies and install only production dependencies
          Remove-Item -Path node_modules -Recurse -Force -ErrorAction SilentlyContinue
          npm ci --omit=dev

      - name: Create deployment package
        run: |
          # Remove unnecessary files and directories
          Remove-Item -Path .git -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path .github -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "*.log" -Force -ErrorAction SilentlyContinue

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !.git/**
            !.github/**
            !.vscode/**
            !*.md
            !*.log
          compression-level: 9

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'easycharter-web'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_55224EA7F94C460A88824DBC3C799B16 }}